### ISSUE TITLE
What is the purpose of this site?

### ISSUE THREAD

**Issue by Tyriar** [DonJayamanne/pythonVSCodeDocs#2]
From what I can see it just rehashes content from the repo, wiki and marketplace. Ideally the link on GitHub would be a direct link to [the marketplace as well](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python). Also in terms of SEO the repo and marketplace links are the top 2 and this site doesn't show up on first page.

**Comment by DonJayamanne** [comment]
@Tyriar 
The plan is to take the contents of this new site:
- Bundle into extension (offline documentation) - this has been done
- and then use the same to update the gh-pages of the Python extension repo (https://github.com/DonJayamanne/pythonVSCode)

This way, both have the same content. I need to fix the start up page (index.md) of this site, so that it matches the page on http://donjayamanne.github.io/pythonVSCode/

Once done:
- Local extension documentation will use the content from this site (offline)
- Wiki will point to this http://donjayamanne.github.io/pythonVSCode/
- And finally, http://donjayamanne.github.io/pythonVSCode/ will use content published form this website.

Hope this makes sense.
If you have any suggestions on improving this let me know.

Once again, all that needs to be done is to fix the [index.md](https://github.com/DonJayamanne/pythonVSCodeDocs/blob/master/pages/index.md) and then publish it to the gh-pages branch of the Python extension repo (https://github.com/DonJayamanne/pythonVSCode)

**Comment by Tyriar** [comment]
Seems like a lot of work and a lot of duplication of documentation just to get offline documentation working. Is there a particular demand for offline documentation or something?

**Comment by DonJayamanne** [comment]
@Tyriar 

> lot of duplication of documentation

Yes, thats until I get that one page fixed. Then there won't be any more duplication.

> Is there a particular demand for offline documentation or something

No, but there have been plenty of questions on how to setup and configure things. Hence thought it would be easy to just bundle the thing into once place and display the local help.
